api/urls.py
from django.urls import path, include

urlpatterns = [
    path('fixture/', include('cricket_app.urls')),
]

cricket_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# root directory used for frontend in nginx
urlpatterns = [
                  #path('admin/', admin.site.urls),
                  path('admin/', include('custom_admin.urls')),
                  path('', include('frontend.urls')),
                  path('api/', include('api.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

custom_admin/urls.py
from django.urls import path
from .views import (Dashboard, Login, Logout, PlayerList, PlayerCreate, PlayerEdit, TeamList, TeamCreate, TeamEdit,
                    FixtureCreate, FixtureList, FixtureEdit, PlayerHistoryEdit)

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('login', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('player_list', PlayerList.as_view(), name='player-list'),
    path('player_create', PlayerCreate.as_view(), name='player-create'),
    path('player_edit/<int:pk>/', PlayerEdit.as_view(), name='player-edit'),
    path('team_list', TeamList.as_view(), name='team-list'),
    path('team_create', TeamCreate.as_view(), name='team-create'),
    path('team_edit/<int:pk>/', TeamEdit.as_view(), name='team-edit'),
    path('fixture_create/', FixtureCreate.as_view(), name='fixture-create'),
    path('fixture_list', FixtureList.as_view(), name='fixture-list'),
    path('fixture_edit/<int:pk>/', FixtureEdit.as_view(), name='fixture-edit'),
    path('player_history_edit/<int:pk>/', PlayerHistoryEdit.as_view(), name='player-history-edit'),
]

custom_admin/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, password):
        """
        Creates and saves a User with the given username, password.
        """
        if not email:
            raise ValueError('Users must have an username')
        user = self.model(email=email)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given username and 	password.
        Apply is_superuser status is TRUE
        """
        user = self.create_user(email=email, password=password)
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    email = models.EmailField(max_length=60, unique=True)
    first_name = models.CharField(max_length=60, blank=True)
    last_name = models.CharField(max_length=60, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='user/profile_images/%Y/%m/%d', default='')

    objects = UserManager()
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        self.validate_unique()
        super(User, self).save(*args, **kwargs)

custom_admin/forms.py
from django import forms
from django.db.models import Q
from cricket_app.models import Player, Team, Fixture, Match
from django.utils.translation import ugettext_lazy as _


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)


class PlayerCreateForm(forms.Form):
    image_uri = forms.ImageField(required=False)
    first_name = forms.CharField(max_length=300, required=True)
    last_name = forms.CharField(max_length=300, required=True)
    jersey_number = forms.IntegerField(max_value=11, min_value=1, required=True)
    country = forms.CharField(max_length=250, required=True)

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if Player.objects.filter(Q(first_name=first_name) & Q(last_name=last_name)).exists():
            raise forms.ValidationError(
                _('A Player with same Name have already existed.'),
                code='name', )
        return self.cleaned_data


class PlayerEditForm(PlayerCreateForm):

    def __init__(self, *args, **kwargs):
        self.pk = kwargs.pop('pk', None)
        super(PlayerEditForm, self).__init__(*args, **kwargs)

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if Player.objects.filter(Q(first_name=first_name) & Q(last_name=last_name)).exclude(pk=self.pk).exists():
            raise forms.ValidationError(
                _('A Player with same Name have already existed.'),
                code='name', )
        return self.cleaned_data


class TeamCreateForm(forms.Form):
    logoUri = forms.ImageField(required=False)
    name = forms.CharField(max_length=300, required=True)
    club_state = forms.CharField(max_length=300, required=True)
    players = forms.MultipleChoiceField(choices=Player.objects.all().values_list('id', 'first_name'), required=False)

    def clean(self):
        name = self.cleaned_data.get('name')
        if Team.objects.filter(name__iexact=name).exists():
            raise forms.ValidationError(
                _('A Player with same Name have already existed.'),
                code='name', )
        return self.cleaned_data


class TeamEditForm(TeamCreateForm):

    def __init__(self, *args, **kwargs):
        self.pk = kwargs.pop('pk', None)
        super(TeamEditForm, self).__init__(*args, **kwargs)

    def clean(self):
        name = self.cleaned_data.get('name')
        if Team.objects.filter(name__iexact=name).exclude(pk=self.pk).exists():
            raise forms.ValidationError(
                _('A Team with same Name have already existed.'),
                code='name', )
        return self.cleaned_data


class FixtureCreateForm(forms.Form):
    name = forms.CharField(max_length=300, required=True)
    teams = forms.MultipleChoiceField(choices=Team.objects.all().values_list('id', 'name'), required=True)


class FixtureEditForm(forms.Form):
    winner = forms.ChoiceField(choices=Team.objects.all().values_list('id', 'name'), required=True)
    score_team1 = forms.IntegerField(required=True)
    score_team2 = forms.IntegerField(required=True)

    def __init__(self, *args, **kwargs):
        self.pk = kwargs.pop('pk', None)
        super(FixtureEditForm, self).__init__(*args, **kwargs)


class PlayerHistoryEditForm(forms.Form):
    run = forms.IntegerField(required=True)

    def __init__(self, *args, **kwargs):
        self.pk = kwargs.pop('pk', None)
        super(PlayerHistoryEditForm, self).__init__(*args, **kwargs)

custom_admin/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView
from cricket_app.models import Player, Team, Fixture, Match, PlayerHistory, Point
from custom_admin.utils import Util
from .forms import LoginForm, PlayerCreateForm, PlayerEditForm, TeamCreateForm, TeamEditForm, FixtureCreateForm, \
    FixtureEditForm, PlayerHistoryEditForm
from django.shortcuts import redirect


class Dashboard(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'custom_admin/dashboard.html'
    login_url = reverse_lazy('login')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request):
        return render(request, self.template_name)


class Login(View):
    template_name = 'custom_admin/account/login.html'
    form_class = LoginForm
    context = dict()

    def get(self, request, *args, **kwargs):
        self.context.clear()
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        self.context.clear()
        form = self.form_class(request.POST)
        self.context['form'] = form
        if form.is_valid():
            user = authenticate(request=request, email=request.POST['email'], password=request.POST['password'])
            if user:
                login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, 'Incorrect Email or Password')
        else:
            error = Util.form_validation_error(request, form)
            self.context['error'] = error
        return render(request, self.template_name, self.context)


class Logout(LoginRequiredMixin, UserPassesTestMixin, View):
    login_url = reverse_lazy('login')

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))


class PlayerList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'custom_admin/player/list.html'
    login_url = reverse_lazy('login')
    queryset = Player.objects.all()
    paginate_by = 10
    context_object_name = 'players'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')


class PlayerCreate(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'custom_admin/player/create.html'
    login_url = reverse_lazy('login')
    form_class = PlayerCreateForm
    context = dict()

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request):
        self.context.clear()
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context.clear()
        form = self.form_class(request.POST, request.FILES)
        self.context['form'] = form
        if form.is_valid():
            print(form.cleaned_data)
            Player.objects.create(
                first_name=form.cleaned_data.get('first_name', ''),
                last_name=form.cleaned_data.get('last_name', ''),
                image_uri=form.cleaned_data.get('image_uri', ''),
                jersey_number=form.cleaned_data.get('jersey_number', 0),
                country=form.cleaned_data.get('country')
            )
            messages.success(self.request, 'Player has been created successfully.')
            return HttpResponseRedirect(reverse('player-list'))
        else:
            error = Util.form_validation_error(request, form)
            self.context['error'] = error
        return render(request, self.template_name, self.context)


class PlayerEdit(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'custom_admin/player/edit.html'
    login_url = reverse_lazy('login')
    form_class = PlayerEditForm
    context = dict()

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request, **kwargs):
        self.context['player'] = Player.objects.get(pk=kwargs['pk'])
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, pk=self.context['player'].id)
        self.context['form'] = form
        if form.is_valid():
            print(form.cleaned_data)
            player = self.context['player']
            player.image_uri = form.cleaned_data.get('image_uri', '') or player.image_uri
            player.first_name = form.cleaned_data.get('first_name')
            player.last_name = form.cleaned_data.get('last_name')
            player.jersey_number = form.cleaned_data.get('jersey_number')
            player.country = form.cleaned_data.get('country')
            player.save()
            messages.success(self.request, 'Player has been updated successfully.')
            return HttpResponseRedirect(reverse('player-list'))
        else:
            error = Util.form_validation_error(request, form)
            self.context['error'] = error
        return render(request, self.template_name, self.context)


class TeamList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'custom_admin/team/list.html'
    login_url = reverse_lazy('login')
    queryset = Team.objects.all()
    paginate_by = 10
    context_object_name = 'teams'

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')


class TeamCreate(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'custom_admin/team/create.html'
    login_url = reverse_lazy('login')
    form_class = TeamCreateForm
    context = dict()

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request):
        self.context.clear()
        selected_player_ids = [player.id for team in Team.objects.all() for player in team.players.all()]
        print(selected_player_ids)
        self.context['players'] = Player.objects.exclude(id__in=selected_player_ids)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context.clear()
        form = self.form_class(request.POST, request.FILES)
        self.context['form'] = form
        if form.is_valid():
            print(form.cleaned_data)
            team = Team.objects.create(
                name=form.cleaned_data.get('name', ''),
                logoUri=form.cleaned_data.get('logoUri', ''),
                club_state=form.cleaned_data.get('club_state', ''),
            )
            player_ids = form.cleaned_data['players']
            players = [player for player in Player.objects.filter(pk__in=player_ids)]
            team.players.add(*players)
            messages.success(self.request, 'Team has been created successfully.')
            return HttpResponseRedirect(reverse('team-list'))
        else:
            error = Util.form_validation_error(request, form)
            self.context['error'] = error
        return render(request, self.template_name, self.context)


class TeamEdit(LoginRequiredMixin, UserPassesTestMixin, View):
    template_name = 'custom_admin/team/edit.html'
    login_url = reverse_lazy('login')
    form_class = TeamEditForm
    context = dict()

    def test_func(self):
        return self.request.user.is_superuser

    def handle_no_permission(self):
        messages.error(self.request, 'Permission denied!!!')
        return redirect('login')

    def get(self, request, **kwargs):
        self.context['team'] = Team.objects.get(pk=kwargs['pk'])
        selected_player_ids = [player.id for team in Team.objects.exclude(id=int(kwargs['pk'])) for player in team.players.all()]
        print(selected_player_ids)
        self.context['players'] = Player.objects.exclude(id__in=selected_player_ids)
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, pk=self.context['team'].id)
        self.context['form'] = form
        print(form.is_valid())
        if form.is_valid():
            print(form.cleaned_data)
            print(form.cleaned_data['players'])
            team = self.context['team']
            team.logoUri = form.cleaned_data.get('logoUri', '') or team.logoUri
            team.name = form.cleaned_data.get('name')
            team.club_state = form.cleaned_data.get('club_state')
            team.players.clear()
            player_ids = form.cleaned_data['players']
            players = [player for player in Player.objects.filter(pk__in=player_ids)]
            team.players.add(*players)
            team.save()
            messages.success(self.request, 'Team has been updated successfully.')
            return HttpResponseRedirect(reverse('team-list'))
        else:

templates/custom_admin/user/list-v1.html
{% extends "custom_admin/index.html" %}
{% load static %}
{% block content %}
<!-- begin:: Subheader -->
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-subheader__main">

        <h3 class="kt-subheader__title">
            Multiple Controls Examples </h3>

        <span class="kt-subheader__separator kt-hidden"></span>
        <div class="kt-subheader__breadcrumbs">
            <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Crud </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Datatables.net </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Advanced </a>
            <span class="kt-subheader__breadcrumbs-separator"></span>
            <a href="#" class="kt-subheader__breadcrumbs-link">
                Multiple Controls </a>
            <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
        </div>

    </div>
    <div class="kt-subheader__toolbar">
        <div class="kt-subheader__wrapper">
            <a href="#" class="btn kt-subheader__btn-primary">
                Actions &nbsp;
                <!--<i class="flaticon2-calendar-1"></i>-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                    height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--sm">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect id="bound" x="0" y="0" width="24" height="24" />
                        <rect id="Rectangle-8" fill="#000000" x="4" y="5" width="16" height="3" rx="1.5" />
                        <path
                            d="M7.5,11 L16.5,11 C17.3284271,11 18,11.6715729 18,12.5 C18,13.3284271 17.3284271,14 16.5,14 L7.5,14 C6.67157288,14 6,13.3284271 6,12.5 C6,11.6715729 6.67157288,11 7.5,11 Z M10.5,17 L13.5,17 C14.3284271,17 15,17.6715729 15,18.5 C15,19.3284271 14.3284271,20 13.5,20 L10.5,20 C9.67157288,20 9,19.3284271 9,18.5 C9,17.6715729 9.67157288,17 10.5,17 Z"
                            id="Combined-Shape" fill="#000000" opacity="0.3" />
                    </g>
                </svg> </a>

            <div class="dropdown dropdown-inline" data-toggle="kt-tooltip" title="Quick actions" data-placement="left">
                <a href="#" class="btn btn-icon" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                        height="24px" viewBox="0 0 24 24" version="1.1"
                        class="kt-svg-icon kt-svg-icon--success kt-svg-icon--md">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                            <path
                                d="M5.85714286,2 L13.7364114,2 C14.0910962,2 14.4343066,2.12568431 14.7051108,2.35473959 L19.4686994,6.3839416 C19.8056532,6.66894833 20,7.08787823 20,7.52920201 L20,20.0833333 C20,21.8738751 19.9795521,22 18.1428571,22 L5.85714286,22 C4.02044787,22 4,21.8738751 4,20.0833333 L4,3.91666667 C4,2.12612489 4.02044787,2 5.85714286,2 Z"
                                id="Combined-Shape" fill="#000000" fill-rule="nonzero" opacity="0.3" />
                            <path
                                d="M11,14 L9,14 C8.44771525,14 8,13.5522847 8,13 C8,12.4477153 8.44771525,12 9,12 L11,12 L11,10 C11,9.44771525 11.4477153,9 12,9 C12.5522847,9 13,9.44771525 13,10 L13,12 L15,12 C15.5522847,12 16,12.4477153 16,13 C16,13.5522847 15.5522847,14 15,14 L13,14 L13,16 C13,16.5522847 12.5522847,17 12,17 C11.4477153,17 11,16.5522847 11,16 L11,14 Z"
                                id="Combined-Shape" fill="#000000" />
                        </g>
                    </svg>
                    <!--<i class="flaticon2-plus"></i>-->
                </a>
                <div class="dropdown-menu dropdown-menu-fit dropdown-menu-md dropdown-menu-right">
                    <!--begin::Nav-->
                    <ul class="kt-nav">
                        <li class="kt-nav__head">
                            Add anything or jump to:
                            <i class="flaticon2-information" data-toggle="kt-tooltip" data-placement="right"
                                title="Click to learn more..."></i>
                        </li>
                        <li class="kt-nav__separator"></li>
                        <li class="kt-nav__item">
                            <a href="#" class="kt-nav__link">
                                <i class="kt-nav__link-icon flaticon2-drop"></i>
                                <span class="kt-nav__link-text">Order</span>
                            </a>
                        </li>
                        <li class="kt-nav__item">
                            <a href="#" class="kt-nav__link">
                                <i class="kt-nav__link-icon flaticon2-calendar-8"></i>
                                <span class="kt-nav__link-text">Ticket</span>
                            </a>
                        </li>
                        <li class="kt-nav__item">
                            <a href="#" class="kt-nav__link">
                                <i class="kt-nav__link-icon flaticon2-link"></i>
                                <span class="kt-nav__link-text">Goal</span>
                            </a>
                        </li>
                        <li class="kt-nav__item">
                            <a href="#" class="kt-nav__link">
                                <i class="kt-nav__link-icon flaticon2-new-email"></i>
                                <span class="kt-nav__link-text">Support Case</span>
                                <span class="kt-nav__link-badge">
                                    <span class="kt-badge kt-badge--success">5</span>
                                </span>
                            </a>
                        </li>
                        <li class="kt-nav__separator"></li>
                        <li class="kt-nav__foot">
                            <a class="btn btn-label-brand btn-bold btn-sm" href="#">Upgrade plan</a>
                            <a class="btn btn-clean btn-bold btn-sm" href="#" data-toggle="kt-tooltip"
                                data-placement="right" title="Click to learn more...">Learn more</a>
                        </li>
                    </ul>
                    <!--end::Nav-->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end:: Subheader -->
<!-- begin:: Content -->
<div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
    {% include 'custom_admin/partials/alert_error.html' %}
    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__head kt-portlet__head--lg">
            <div class="kt-portlet__head-label">
                <span class="kt-portlet__head-icon">
                    <i class="kt-font-brand flaticon2-line-chart"></i>
                </span>
                <h3 class="kt-portlet__head-title">
                    Multiple Controls
                </h3>
            </div>
            <div class="kt-portlet__head-toolbar">
                <div class="kt-portlet__head-wrapper">
                    <div class="kt-portlet__head-actions">
                        <div class="dropdown dropdown-inline">
                            <button type="button" class="btn btn-default btn-icon-sm dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="la la-download"></i> Export
                            </button>
                            <div class="dropdown-menu dropdown-menu-right">
                                <ul class="kt-nav">
                                    <li class="kt-nav__section kt-nav__section--first">
                                        <span class="kt-nav__section-text">Choose an option</span>
                                    </li>
                                    <li class="kt-nav__item">
                                        <a href="#" class="kt-nav__link">
                                            <i class="kt-nav__link-icon la la-print"></i>
                                            <span class="kt-nav__link-text">Print</span>
                                        </a>
                                    </li>
                                    <li class="kt-nav__item">
                                        <a href="#" class="kt-nav__link">
                                            <i class="kt-nav__link-icon la la-copy"></i>
                                            <span class="kt-nav__link-text">Copy</span>
                                        </a>
                                    </li>
                                    <li class="kt-nav__item">
                                        <a href="#" class="kt-nav__link">
                                            <i class="kt-nav__link-icon la la-file-excel-o"></i>
                                            <span class="kt-nav__link-text">Excel</span>
                                        </a>
                                    </li>
                                    <li class="kt-nav__item">
                                        <a href="#" class="kt-nav__link">
                                            <i class="kt-nav__link-icon la la-file-text-o"></i>
                                            <span class="kt-nav__link-text">CSV</span>
                                        </a>
                                    </li>
                                    <li class="kt-nav__item">
                                        <a href="#" class="kt-nav__link">
                                            <i class="kt-nav__link-icon la la-file-pdf-o"></i>
                                            <span class="kt-nav__link-text">PDF</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        &nbsp;
                        <a href="{% url 'blog-create' %}" class="btn btn-brand btn-elevate btn-icon-sm">
                            <i class="la la-plus"></i>
                            New Record
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="kt-portlet__body">
            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Email</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Is Active?</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    {% for user in user_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if user.avatar %}
                            <img src="{{MEDIA_URL}}{{ blog.created_by.avatar }}" width="30" height="30" class="rounded-circle">
                            {% else %}
                            <div class="kt-badge kt-badge--md kt-badge--brand">{{ user.email.0 | title }}</div>
                            {% endif %}
                            {{ user.email }}
                        </td>
                        <td>{{ user.first_name | title }} {{ user.last_name | title }}</td>
                        <td>{{ user.phone }}</td>
                        <td>{% if user.is_active %}Yes{% else %}No{% endif %}</td>
                        <td nowrap>
                            <a href="{% url 'user-edit' pk=user.id %}" title="Edit details" class="btn btn-sm btn-clean btn-icon btn-icon-md"> <i class="la la-edit"></i> </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
            <!--end: Datatable -->
        </div>
    </div>
</div>
<!-- end:: Content -->

{% endblock content %}